name: DIY Steward

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  steward:
    runs-on: ubuntu-22.04
    name: DIY Steward
    steps:
      - uses: actions/checkout@v4
          
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: 243680
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.72.0
        with:
          author-email: 243680+nafg-scala-steward[bot]@users.noreply.github.com
          author-name: nafg-scala-steward[bot]
          github-app-id: 243680
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
          github-token: ${{ steps.generate-token.outputs.token }}
          mill-version: 0.12.2
